// <auto-generated />
using System;
using System.Collections.Generic;
using CanterburyUnderwater.PortalApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CanterburyUnderwater.PortalApi.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20250824042414_AddBookings")]
    partial class AddBookings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BondStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("BookingRatePlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ContractHolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PrimaryContactId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<HashSet<int>>("Rooms")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingRatePlanId");

                    b.HasIndex("ContractHolderId");

                    b.HasIndex("PrimaryContactId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeBracket")
                        .HasColumnType("integer");

                    b.Property<int?>("AttendeeType")
                        .HasColumnType("integer");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MembershipNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("LinkedUserId");

                    b.ToTable("BookingAttendees");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingContractHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BookingContractHolders");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Basis")
                        .HasColumnType("integer");

                    b.Property<Guid>("BookingRatePlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingRatePlanId", "Name")
                        .IsUnique();

                    b.ToTable("BookingFees");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeBracket")
                        .HasColumnType("integer");

                    b.Property<int?>("AttendeeType")
                        .HasColumnType("integer");

                    b.Property<Guid>("BookingRatePlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractHolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RateType")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractHolderId");

                    b.HasIndex("BookingRatePlanId", "RateType", "ContractHolderId")
                        .IsUnique();

                    b.HasIndex("BookingRatePlanId", "RateType", "AttendeeType", "AgeBracket")
                        .IsUnique();

                    b.ToTable("BookingRates");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingRatePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BookingRatePlans");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f119827-937c-4546-a576-e9a0118102c5"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("249b7d49-5495-4b3f-87ea-2ebb2bbd6910"),
                            Name = "Committee"
                        });
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FirebaseUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastSignedIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MembershipEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MembershipNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MembershipStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MembershipStatus")
                        .HasColumnType("integer");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.Booking", b =>
                {
                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingRatePlan", "BookingRatePlan")
                        .WithMany()
                        .HasForeignKey("BookingRatePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingContractHolder", "ContractHolder")
                        .WithMany()
                        .HasForeignKey("ContractHolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.User", "PrimaryContact")
                        .WithMany()
                        .HasForeignKey("PrimaryContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingRatePlan");

                    b.Navigation("ContractHolder");

                    b.Navigation("PrimaryContact");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingAttendee", b =>
                {
                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.Booking", "Booking")
                        .WithMany("Attendees")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.User", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("LinkedUser");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingFee", b =>
                {
                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingRatePlan", "BookingRatePlan")
                        .WithMany("Fees")
                        .HasForeignKey("BookingRatePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingRatePlan");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingRate", b =>
                {
                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingRatePlan", "BookingRatePlan")
                        .WithMany("Rates")
                        .HasForeignKey("BookingRatePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingContractHolder", "ContractHolder")
                        .WithMany()
                        .HasForeignKey("ContractHolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BookingRatePlan");

                    b.Navigation("ContractHolder");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanterburyUnderwater.PortalApi.DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.Booking", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("CanterburyUnderwater.PortalApi.DataAccess.Entities.BookingRatePlan", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
